### ISSUE TITLE
sections and section headers

### ISSUE THREAD

**Issue by pverkind** [OpenITI/oitei#2]
Currently, mARkdown text like this: 

```
### | Section 1
# para 1
### || Section 2
# para 2
```

is converted to: 

```
      <div>
        <head>Section 1</head>
        <p>
          <lb/>para 1
        </p>
        <div>
          <head>Section 2</head>
          <p>
            <lb/>para 2
        </div>
      </div>
```

Does TEI have a way to encode the level of the section in the div tag? something like `<div level=1>` for `### |  `?

**Comment by raffazizzi** [comment]
While there are numbered div elements (`<div1>`, `<div2>`, etc.) it is preferable to rely on the hierarchy to determine the level. In your example, the Section 2 `<div>` is second level because it is nested inside one and only one `<div>`.

**Comment by raffazizzi** [comment]
I'm closing this as I think it's preferable to rely on hierarchy as I explained in the previous comment. This is a common operation when working with XML both in a sax (keep a stack) and DOM environment (count ancestor divs).
