### ISSUE TITLE
spaces before named entity tags

### ISSUE THREAD

**Issue by pverkind** [OpenITI/oitei#5]
this line: 

```
# check topo @T02 Madinat assalam correct ?
```

is converted to: 

```
<p>
    <lb/>check topo<placeName>Madinat assalam </placeName> correct ?
</p>
```

A space should be inserted before the placename tag; now it is added after the space tag.

**Comment by raffazizzi** [comment]
Fixed by https://github.com/OpenITI/oitei/commit/ce8e30bd3ad2d8dbfbd1d9be7233bf2274daa43c
