### ISSUE TITLE
`TextPart`s after specific Content should become title headers

### ISSUE THREAD

**Issue by raffazizzi** [OpenITI/oitei#8]
This was originally reported as an issue for `oimdp`: https://github.com/OpenITI/oimdp/issues/7

A `TextPart` immediately following `DictionaryUnit` and `BioOrEvent` should be treated as a header for that section.

> If a dictionary lemma tag like `### $ `, `### $BIO_MAN$ `, ... is followed on the same line by some words, these words need to be interpreted as the title of that lemma. (similar to the `### | `, `### || `, etc. tags)
>
> In oitei, that should lead to this section: 
>
> ```
> ### $ Abu ʿUmar
> # Abu ʿUmar studied with Abu Husayn.
> ~~He had a very good memory
> ```
>
> to be converted to:
>
> ```
> <div type="biography" subtype="man">
>    <head>Abu ʿUmar</head>
>    <p>
>        <lb/>Abu ʿUmar studied with Abu Husayn.
>        <lb/>He had a very good memory
>    </p>
> </div>
> ```
>
> Currently, it is converted like this: 
>
> ```
> <div type="biography" subtype="man">
>    <p>
>        <lb/>Abu ʿUmar
>    </p>
>    <p>
>        <lb/>Abu ʿUmar studied with Abu Husayn.
>        <lb/>He had a very good memory
>    </p>
> </div>
> ```

**Comment by raffazizzi** [comment]
@pverkind is this just for the following two classes or are there others that should be included? (It may be helpful to take a quick look at the [docs](https://openiti.org/oimdp/oimdp.structures.html) to get a sense of the classes, though there isn't a mapping to the tags -- I should add that!) 

* `DictionaryUnit`: `### $`, `### $BIO_MAN`, etc.
* `BioOrEvent`: `### $DIC_NIS$`, etc.

**Comment by raffazizzi** [comment]
Note to self: this may actually be a `oimdp` issue since `SectionHeader` classes include the title as `value`. These unit headers should be handled similarly

**Comment by pverkind** [comment]
@raffazizzi this goes for all section types described in the "Main information units" part of https://alraqmiyyat.github.io/mARkdown/ (and of course also for the `### | `, `### || `, ...) tags. 
I guess this refers to these entities you describe in the documentation:

* [BioOrEvent](https://openiti.org/oimdp/oimdp.structures.html#BioOrEvent)
* [DictionaryUnit](https://openiti.org/oimdp/oimdp.structures.html#DictionaryUnit)
* [DoxographicalItem](https://openiti.org/oimdp/oimdp.structures.html#DoxographicalItem)
* [SectionHeader](https://openiti.org/oimdp/oimdp.structures.html#SectionHeader)

Question: what mARkdown tag does BioOrEvent represent?

**Comment by raffazizzi** [comment]
Thanks @pverkind !



> Question: what mARkdown tag does BioOrEvent represent?

See this section on the mARkdown specs: https://alraqmiyyat.github.io/mARkdown/#-biographies-and-events

**Comment by pverkind** [comment]
Hi @raffazizzi, I was wondering why there is a need for a tag for Bio **OR** Event because mARkdown has clearly separate tags for biographical elements and event elements: 

BIO: 

```
## $ [a biography of a man]
### $$ [a biography of a woman]
### $$$ [a cross-reference and/or repetition, for both men and women]
### $$$$ [a list of names]
### $BIO_MAN$ [a biography of a man]
### $BIO_WOM$ [a biography of a woman]
### $BIO_REF$ [a cross-reference, for both men and women]
### $BIO_NLI$ [a list of names]
```

EVENT: 

```
### @ [a historical event]
### @ RAW [a batch of historical events]
### $CHR_EVE$ [a historical event]
### $CHR_RAW$ [a batch of historical events]
```

**Comment by raffazizzi** [comment]
I see, it's because they're discussed together in the documentation. I agree that it makes sense to distinguish them so I'll update `oimdp`
